Only install Java when parent image doesn't have it. (#27)

diff --git a/variants/browsers.Dockerfile.template b/variants/browsers.Dockerfile.template
--- a/variants/browsers.Dockerfile.template
+++ b/variants/browsers.Dockerfile.template
@@ -11,12 +11,21 @@ RUN curl -sSL -o selenium-server-standalone-${SELENIUM_VER}.jar "https://seleniu
     rm selenium-server-standalone-${SELENIUM_VER}.jar
 
 RUN sudo apt-get update && \
+
+    # Install Java only if it's not already available
+    # Java is installed for Selenium
+    if ! command -v java > /dev/null; then \
+        echo "Java not found in parent image, installing..." && \
+        sudo apt-get install -y --no-install-recommends --no-upgrade openjdk-11-jre; \
+    fi && \
+
     # Firefox deps
     sudo apt-get install -y --no-install-recommends --no-upgrade \
 		libdbus-glib-1-2 \
 		libgtk-3-dev \
 		libxt6 \
 	&& \
+
     # Google Chrome deps
 	# Some of these packages should be pulled into their own section
     sudo apt-get install -y --no-install-recommends --no-upgrade \
@@ -33,8 +42,6 @@ RUN sudo apt-get update && \
         libpango-1.0-0 \
         libpangocairo-1.0-0 \
         libxcursor1 \
-        # java for selenium
-        openjdk-11-jre \
         xdg-utils \
 		xvfb \
 	&& \
